/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi.yeneli;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author 52753
 */
public class PanelControl extends javax.swing.JFrame {
    
     int n=0;
     LinkedList <Punto> listaPuntos = new LinkedList();  
     Punto obj = new Punto();
     FiguraG objf= new FiguraG();
     Rectangulo objRec= new Rectangulo();
     int contadorIngresos=0;
     int anchoFigura;
     int altoFigura;
     int opcion;
    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tY = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LPerimetro = new javax.swing.JLabel();
        LArea = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        areaDibujo1 = new edu.unicundi.yeneli.AreaDibujo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        botonIngresar.setText("INGRESAR COORDENADAS");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("INGRESA X");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("INGRESA Y");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("AREA");

        LPerimetro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("PERIMETRO");

        javax.swing.GroupLayout areaDibujo1Layout = new javax.swing.GroupLayout(areaDibujo1);
        areaDibujo1.setLayout(areaDibujo1Layout);
        areaDibujo1Layout.setHorizontalGroup(
            areaDibujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        areaDibujo1Layout.setVerticalGroup(
            areaDibujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(areaDibujo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tY, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(12, 12, 12)
                                .addComponent(LPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(LArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(botonIngresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(botonIngresar)
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(LArea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(areaDibujo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Opcion(){
         opcion = Integer.parseInt(JOptionPane.showInputDialog("¿Que quieres Dibujar? \n 1.-Cuadrado \n 2.-Rectangulo \n 3.-Triangulo"));
        
        if (opcion==1 || opcion==2){
            n=4;
        }
        if (opcion==3){
            n=3;
        }
        if (opcion>3 ||  opcion<1){
            Opcion();
        }
        
    }
    
    public void ingresarALista(){
        
        int x=0;
        int y=0;
       
        x = Integer.parseInt(this.tX.getText());
        y = Integer.parseInt(this.tY.getText());
        Punto obj = new Punto();
       obj.setX(x);
       obj.setY(y);

       listaPuntos.add(obj);

       for(int c=0; c<listaPuntos.size(); c++){
           System.out.println("++X="+ listaPuntos.get(c).getX()+ "Y="+ listaPuntos.get(c).getY());
       }
       tX.setText(null);
       tY.setText(null);
       
       contadorIngresos++;
       
       
    }
    
    public void CalcularAnchoYAlto(){
        anchoFigura=(listaPuntos.get(1).getX()-listaPuntos.get(0).getX());
        System.out.println("Anchhoo " +anchoFigura);
        altoFigura=(listaPuntos.get(2).getY()-listaPuntos.get(1).getY());
        System.out.println("AnLTO " +altoFigura);
        
        
        
    }
    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
      if (n==0){
          Opcion();
      }
      System.out.println(""+n);

      if (contadorIngresos<n-1){
          ingresarALista();
          System.out.println("lll contadorIngresos "+contadorIngresos);
          return;
          
      } if (contadorIngresos==3){
          ingresarALista();
          System.out.println("2 contadorIngresos "+contadorIngresos);
      }
      
       CalcularAnchoYAlto();
       
//      objf.ValidarCoordenadas(listaPuntos,altoFigura,anchoFigura);
       int retornaValidacion= objf.ValidarCoordenadas(listaPuntos,altoFigura,anchoFigura);
       
       if(retornaValidacion==opcion){
           MandarDibujar();
       }
       if(retornaValidacion!=opcion){
           JOptionPane.showMessageDialog(null, "LAS COORDENADAS NO CONCUERDAN CON LA FIGURA SELECCIONADA");
       }
       
       
       
    }//GEN-LAST:event_botonIngresarActionPerformed
    public void MandarDibujar(){
       
        //Enviar coordenadas iniciales 
       areaDibujo1.CoordenadasXY(listaPuntos.get(0).getX(),listaPuntos.get(0).getY());
       
       for(int c=0; c<listaPuntos.size(); c++){
           System.out.println("X="+ listaPuntos.get(c).getX()+ "Y="+ listaPuntos.get(c).getY());
       }
       areaDibujo1.EnviarAnchoAlto(altoFigura, anchoFigura);
       
       areaDibujo1.Actualizar();

       if(opcion==1 || opcion==2){
           LArea.setText(""+objf.CalcularArea(altoFigura,anchoFigura));
           if(opcion==1){
           LPerimetro.setText(""+objf.CalcularPerimetro(altoFigura,anchoFigura));
            }
           if(opcion==2){
           LPerimetro.setText(""+objRec.CalcularPerimetro(altoFigura,anchoFigura));
            }
       }
       
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LArea;
    private javax.swing.JLabel LPerimetro;
    private edu.unicundi.yeneli.AreaDibujo areaDibujo1;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tX;
    private javax.swing.JTextField tY;
    // End of variables declaration//GEN-END:variables
}
