/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi.yeneli;

import java.text.DecimalFormat;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *Clase Panel de Control 
 * @author Yeneli Garcia M
 */
public class PanelControl extends javax.swing.JFrame {
   
    ///Variable que guarda la cantidad de puntos de cada Figura
     int numPuntos=0;
     //Lista que guarda los puntos de la figura
     LinkedList <Punto> listaPuntos = new LinkedList();  
     //Objeto tipo Punto 
     Punto obj = new Punto();
     //Objeto tipo FiguraG
     FiguraG objf= new FiguraG();
     //Objeto tipo Rectangulo
     Rectangulo objRec= new Rectangulo();
     //Objeto tipo triangulo
     Triangulo t = new Triangulo();
     //Contador de coordenadas(puntos) ingresadas por el usuario
     int contadorIngresos=0;
     //Ancho de la figura
     int anchoFigura;
     //Alto de la figura
     int altoFigura;
     //Variable que guarda la opcion del usuario
     int opcion;
     //Formato de decimales para la impresion de areas y perimetros
     
     DecimalFormat df = new DecimalFormat("#0.0000");
     
     
    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tY = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LPerimetro = new javax.swing.JLabel();
        LArea = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        areaDibujo1 = new edu.unicundi.yeneli.AreaDibujo();
        LTipoTriangulo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        botonIngresar.setText("INGRESAR COORDENADAS");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("INGRESA X");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("INGRESA Y");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("AREA");

        LPerimetro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("PERIMETRO");

        javax.swing.GroupLayout areaDibujo1Layout = new javax.swing.GroupLayout(areaDibujo1);
        areaDibujo1.setLayout(areaDibujo1Layout);
        areaDibujo1Layout.setHorizontalGroup(
            areaDibujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        areaDibujo1Layout.setVerticalGroup(
            areaDibujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        LTipoTriangulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unicundi/yeneli/imagenes/ejemploT.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unicundi/yeneli/imagenes/ejemploC.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(areaDibujo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(12, 12, 12)
                                        .addComponent(LPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 12, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(LArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(LTipoTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tY, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(tX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(36, 36, 36)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(botonIngresar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonIngresar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(LArea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(LTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(areaDibujo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(63, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Metodo donde se agregan las coordenadas
 * a la lista, asi mismo, llama al metodo para dibujar
 * dependiendo de la opcion del usuario
 * @param evt 
 */
    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        //Condicion que ejecuta el metodo Opcion
        if (numPuntos==0){
            Opcion();
        }
        //Condicion que agrega los puntos a la lista 
        if (contadorIngresos<numPuntos-1){
            ingresarALista();
            return;
            
        } if (contadorIngresos==numPuntos-1){
            ingresarALista();
        }
        
        if(opcion==1 || opcion==2){
            CalcularAnchoYAlto(); 
           //Se mandan a llamar el metodo que valida si las coordenadas coinciden con la opcion del usuario
            int retornaValidacion= objf.ValidarCoordenadas(listaPuntos,altoFigura,anchoFigura);
         
            if(retornaValidacion==opcion){
                MandarDibujar();
            }
            if(retornaValidacion!=opcion){
                JOptionPane.showMessageDialog(null, "LAS COORDENADAS NO CONCUERDAN CON LA FIGURA SELECCIONADA");
                return;
            }

        }
       

        MandarDibujar();

    }//GEN-LAST:event_botonIngresarActionPerformed

    
    /**
     * Metodo que recibe la opcion del usuario y lo guarda
     * en la variable opcion, asi mismo, se asigna el numero
     * de puntos que tiene cada figura
     */
    public void Opcion(){
         opcion = Integer.parseInt(JOptionPane.showInputDialog("¿Que quieres Dibujar? \n 1.-Cuadrado \n 2.-Rectangulo \n 3.-Triangulo"));
        
        if (opcion==1 || opcion==2){
            numPuntos=4;
        }
        if (opcion==3){
            numPuntos=3;
        }
        if (opcion>3 ||  opcion<1){
            Opcion();
        }
    }
    
    /**
     * Metodo que ingresa los objetos tipo punto (las coordenadas)
     * a la lista.
     */
    public void ingresarALista(){
        
        int x=0;
        int y=0;
       //Se extraen las coordenadas 
        x = Integer.parseInt(this.tX.getText());
        y = Integer.parseInt(this.tY.getText());
        Punto obj = new Punto();
       obj.setX(x);
       obj.setY(y);

       listaPuntos.add(obj);

      //Se limpian los campos
       tX.setText(null);
       tY.setText(null);
       //Incrementa el numero de ingresos del usuario
       contadorIngresos++;
       
       
    }
    /**
     * Se calcula el alto y el ancho de la figura
     */
    public void CalcularAnchoYAlto(){
        anchoFigura=(listaPuntos.get(1).getX()-listaPuntos.get(0).getX());
        
        altoFigura=(listaPuntos.get(2).getY()-listaPuntos.get(1).getY());
       
        
    } 
    /**
     * Metodo que ejecuta los metodos de dibujo
     * de las figuras, asi mismo los metodos de
     * calculo de area y perimetro
     */
    public void MandarDibujar(){
       areaDibujo1.opcion=opcion;
        
        //Enviar coordenadas iniciales 
       areaDibujo1.CoordenadasXY(listaPuntos.get(0).getX(),listaPuntos.get(0).getY());
       
       if (opcion==1 || opcion==2){
       areaDibujo1.EnviarAnchoAlto(altoFigura, anchoFigura);
       }
       if (opcion==3){
           areaDibujo1.listaPuntos=listaPuntos;
       }
       
       areaDibujo1.Actualizar();
       
       if(opcion==1 || opcion==2){
           LArea.setText(""+objf.CalcularArea(altoFigura,anchoFigura));
           if(opcion==1){
           LPerimetro.setText(""+objf.CalcularPerimetro(altoFigura,anchoFigura));
            }
           if(opcion==2){
           LPerimetro.setText(""+objRec.CalcularPerimetro(altoFigura,anchoFigura));
            }
       }
       if(opcion==3){
           t.setListaPuntos(listaPuntos);
           LPerimetro.setText(""+df.format(t.Perimetro()));
           t.IdentificarTriangulo();
           LTipoTriangulo.setText("TRIANGULO "+t.getTipoTriangulo());
           LArea.setText(""+df.format(t.HallarAreas()));
       }
       
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LArea;
    private javax.swing.JLabel LPerimetro;
    private javax.swing.JLabel LTipoTriangulo;
    private edu.unicundi.yeneli.AreaDibujo areaDibujo1;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tX;
    private javax.swing.JTextField tY;
    // End of variables declaration//GEN-END:variables
}
